/*
 * Copyright (C) 2026 Amalgam Solucoes em TI Ltda.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as assert from 'assert';
import {promises as fs} from 'fs';
import * as os from 'os';
import * as path from 'path';
import {removeLegacyEclipseMetadata, synchronizeGradlePreviewConfig, validateGradlePreviewTasks, writeAndValidateGradleProject} from '../../migration/convert-project';

suite('Maven to Gradle conversion transaction', () => {
    test('preserves the POM only after successful validation and keeps unrelated properties', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-success-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            await fs.writeFile(path.join(root, 'gradle.properties'), 'other=value\n');
            await fs.writeFile(path.join(root, '.classpath'), 'maven classpath');
            await fs.writeFile(path.join(root, '.project'), 'maven project');
            await fs.mkdir(path.join(root, '.settings'), {recursive: true});
            await fs.writeFile(path.join(root, '.settings/org.eclipse.m2e.core.prefs'), 'maven settings');
            await fs.writeFile(path.join(root, 'totalcross.preview.json'), JSON.stringify({
                mainWindow: 'com.example.MainWindow',
                buildCommand: 'mvn compile',
                classOutputPaths: ['target/classes'],
                resourcePaths: ['src/main/resources'],
                dependencyPaths: ['target/lib'],
                headlessOutput: 'target/totalcross-preview/preview.png'
            }));
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', '// Generated by TotalCross Maven-to-Gradle migration.\n');
            files.set('gradlew', '#!/bin/sh\n');
            files.set('gradle.properties', 'totalcrossActivationKey=secret\n');
            const result = await writeAndValidateGradleProject(root, {files, sensitiveFiles: ['gradle.properties']}, () => Promise.resolve());
            assert.equal(result, 'converted');
            assert.equal(await exists(path.join(root, 'pom.xml')), false);
            assert.equal(await exists(path.join(root, 'pom.xml.maven-backup')), true);
            assert.equal(await exists(path.join(root, '.classpath')), false);
            assert.equal(await exists(path.join(root, '.project')), false);
            assert.equal(await exists(path.join(root, '.settings/org.eclipse.m2e.core.prefs')), false);
            assert.equal(await fs.readFile(path.join(root, 'gradle.properties'), 'utf8'), 'other=value\ntotalcrossActivationKey=secret\n');
            const preview = JSON.parse(await fs.readFile(path.join(root, 'totalcross.preview.json'), 'utf8'));
            assert.equal(preview.mainWindow, 'com.example.MainWindow');
            assert.equal(preview.buildCommand, './gradlew classes');
            assert.deepEqual(preview.classOutputPaths, ['build/classes/java/main']);
            assert.deepEqual(preview.dependencyPaths, ['build/libs']);
            assert.equal(preview.headlessOutput, 'build/totalcross-preview/preview.png');
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('restores modified files after validation failure', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-rollback-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            await fs.writeFile(path.join(root, 'build.gradle'), 'original');
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', 'replacement');
            await assert.rejects(writeAndValidateGradleProject(root, {files, sensitiveFiles: []}, () => Promise.reject(new Error('validation failed'))), /validation failed/);
            assert.equal(await fs.readFile(path.join(root, 'build.gradle'), 'utf8'), 'original');
            assert.equal(await exists(path.join(root, 'pom.xml')), true);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('keeps generated files and the POM when Maven Local lacks the plugin', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-local-plugin-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', 'generated');
            const result = await writeAndValidateGradleProject(root, {files, sensitiveFiles: []}, () => Promise.reject(new Error('Could not resolve com.totalcross.application plugin: not found')));
            assert.equal(result, 'plugin-not-local');
            assert.equal(await fs.readFile(path.join(root, 'build.gradle'), 'utf8'), 'generated');
            assert.equal(await exists(path.join(root, 'pom.xml')), true);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('repairs a stale Maven preview descriptor in an existing generated Gradle project', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-preview-config-repair-'));
        try {
            await fs.writeFile(path.join(root, 'totalcross.preview.json'), JSON.stringify({
                mainWindow: 'com.example.MainWindow', buildCommand: 'mvn compile', classOutputPaths: ['target/classes']
            }));
            assert.equal(await synchronizeGradlePreviewConfig(root), true);
            const preview = JSON.parse(await fs.readFile(path.join(root, 'totalcross.preview.json'), 'utf8'));
            assert.equal(preview.mainWindow, 'com.example.MainWindow');
            assert.equal(preview.buildCommand, './gradlew classes');
            assert.deepEqual(preview.classOutputPaths, ['build/classes/java/main']);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('rejects a Gradle plugin without the preview and run tasks', () => {
        assert.throws(
            () => validateGradlePreviewTasks('totalcrossPackage - Packages the application'),
            /does not provide totalcrossPreview and totalcrossRun/
        );
        assert.doesNotThrow(() => validateGradlePreviewTasks('totalcrossPreview\ntotalcrossRun\n'));
    });

    test('cleans stale Eclipse metadata when revisiting an already generated Gradle project', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-gradle-metadata-repair-'));
        try {
            await fs.writeFile(path.join(root, '.classpath'), 'maven classpath');
            await fs.writeFile(path.join(root, '.project'), 'maven project');
            await fs.mkdir(path.join(root, '.settings'), {recursive: true});
            await fs.writeFile(path.join(root, '.settings/org.eclipse.m2e.core.prefs'), 'maven settings');
            await removeLegacyEclipseMetadata(root);
            assert.equal(await exists(path.join(root, '.classpath')), false);
            assert.equal(await exists(path.join(root, '.project')), false);
            assert.equal(await exists(path.join(root, '.settings/org.eclipse.m2e.core.prefs')), false);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });
});

async function exists(file: string): Promise<boolean> { try { await fs.access(file); return true; } catch (_) { return false; } }
