// Copyright (C) 2026 Amalgam Solucoes em TI Ltda.
// SPDX-License-Identifier: Apache-2.0

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'tooling-java'
include 'tooling-core'
include 'tooling-protocol'
include 'preview-worker'
include 'preview-host'
include 'tooling-cli'
include 'tooling-project-conversion'
