// Copyright (C) 2026 Amalgam Solucoes em TI Ltda.
// SPDX-License-Identifier: Apache-2.0

plugins {
    id 'java-library'
    id 'maven-publish'
}

java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }

dependencies {
    api project(':tooling-core')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

tasks.withType(Test).configureEach { useJUnitPlatform() }

tasks.named('processResources') {
    from(rootProject.file('gradlew')) { into 'gradle-wrapper'; rename { 'gradlew' } }
    from(rootProject.file('gradlew.bat')) { into 'gradle-wrapper'; rename { 'gradlew.bat' } }
    from(rootProject.file('gradle/wrapper/gradle-wrapper.jar')) { into 'gradle-wrapper/gradle/wrapper' }
    from(rootProject.file('gradle/wrapper/gradle-wrapper.properties')) { into 'gradle-wrapper/gradle/wrapper' }
}

publishing {
    publications { maven(MavenPublication) { from components.java } }
}
