# Copyright (C) 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: Apache-2.0

schemaVersion=1

entry.temurin-11.0.28-6-macos-arm64.vendor=EclipseAdoptium
entry.temurin-11.0.28-6-macos-arm64.javaMajor=11
entry.temurin-11.0.28-6-macos-arm64.version=11.0.28
entry.temurin-11.0.28-6-macos-arm64.build=6
entry.temurin-11.0.28-6-macos-arm64.operatingSystem=Mac OS X
entry.temurin-11.0.28-6-macos-arm64.architecture=aarch64
entry.temurin-11.0.28-6-macos-arm64.archiveType=tar.gz
entry.temurin-11.0.28-6-macos-arm64.url=https\://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.28%2B6/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.28_6.tar.gz
entry.temurin-11.0.28-6-macos-arm64.sha256=b5b46eb84aa2f301e739178aef0209c6843d6ad45b33f19dd39df4decdd29e9e
entry.temurin-11.0.28-6-macos-arm64.javaHomeRelativePath=jdk-11.0.28+6/Contents/Home

entry.temurin-11.0.28-6-macos-x64.vendor=EclipseAdoptium
entry.temurin-11.0.28-6-macos-x64.javaMajor=11
entry.temurin-11.0.28-6-macos-x64.version=11.0.28
entry.temurin-11.0.28-6-macos-x64.build=6
entry.temurin-11.0.28-6-macos-x64.operatingSystem=Mac OS X
entry.temurin-11.0.28-6-macos-x64.architecture=x86_64
entry.temurin-11.0.28-6-macos-x64.archiveType=tar.gz
entry.temurin-11.0.28-6-macos-x64.url=https\://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.28%2B6/OpenJDK11U-jdk_x64_mac_hotspot_11.0.28_6.tar.gz
entry.temurin-11.0.28-6-macos-x64.sha256=4683f3b751310bfd228a5a64e6ee643e9f1ccadd38b4bac3d74597dbf6d5d57a
entry.temurin-11.0.28-6-macos-x64.javaHomeRelativePath=jdk-11.0.28+6/Contents/Home

entry.temurin-11.0.28-6-linux-x64.vendor=EclipseAdoptium
entry.temurin-11.0.28-6-linux-x64.javaMajor=11
entry.temurin-11.0.28-6-linux-x64.version=11.0.28
entry.temurin-11.0.28-6-linux-x64.build=6
entry.temurin-11.0.28-6-linux-x64.operatingSystem=Linux
entry.temurin-11.0.28-6-linux-x64.architecture=amd64
entry.temurin-11.0.28-6-linux-x64.archiveType=tar.gz
entry.temurin-11.0.28-6-linux-x64.url=https\://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.28%2B6/OpenJDK11U-jdk_x64_linux_hotspot_11.0.28_6.tar.gz
entry.temurin-11.0.28-6-linux-x64.sha256=7dfd551795a8884b26cbb02e0301da95db40160bb194f48271dc2ef9367f50c2
entry.temurin-11.0.28-6-linux-x64.javaHomeRelativePath=jdk-11.0.28+6

entry.temurin-11.0.28-6-windows-x64.vendor=EclipseAdoptium
entry.temurin-11.0.28-6-windows-x64.javaMajor=11
entry.temurin-11.0.28-6-windows-x64.version=11.0.28
entry.temurin-11.0.28-6-windows-x64.build=6
entry.temurin-11.0.28-6-windows-x64.operatingSystem=Windows 11
entry.temurin-11.0.28-6-windows-x64.architecture=amd64
entry.temurin-11.0.28-6-windows-x64.archiveType=zip
entry.temurin-11.0.28-6-windows-x64.url=https\://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.28%2B6/OpenJDK11U-jdk_x64_windows_hotspot_11.0.28_6.zip
entry.temurin-11.0.28-6-windows-x64.sha256=1422b070f94c93d3fdba7e0bcaa269389c92a928de54e47d988a1002d3a35dc2
entry.temurin-11.0.28-6-windows-x64.javaHomeRelativePath=jdk-11.0.28+6

entry.temurin-17.0.16-8-macos-arm64.vendor=EclipseAdoptium
entry.temurin-17.0.16-8-macos-arm64.javaMajor=17
entry.temurin-17.0.16-8-macos-arm64.version=17.0.16
entry.temurin-17.0.16-8-macos-arm64.build=8
entry.temurin-17.0.16-8-macos-arm64.operatingSystem=Mac OS X
entry.temurin-17.0.16-8-macos-arm64.architecture=aarch64
entry.temurin-17.0.16-8-macos-arm64.archiveType=tar.gz
entry.temurin-17.0.16-8-macos-arm64.url=https\://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.16%2B8/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.16_8.tar.gz
entry.temurin-17.0.16-8-macos-arm64.sha256=f9845abc8403f1d489402201064e7b9f2c57605d8717b85a95a15d94f882eeb7
entry.temurin-17.0.16-8-macos-arm64.javaHomeRelativePath=jdk-17.0.16+8/Contents/Home

entry.temurin-17.0.16-8-macos-x64.vendor=EclipseAdoptium
entry.temurin-17.0.16-8-macos-x64.javaMajor=17
entry.temurin-17.0.16-8-macos-x64.version=17.0.16
entry.temurin-17.0.16-8-macos-x64.build=8
entry.temurin-17.0.16-8-macos-x64.operatingSystem=Mac OS X
entry.temurin-17.0.16-8-macos-x64.architecture=x86_64
entry.temurin-17.0.16-8-macos-x64.archiveType=tar.gz
entry.temurin-17.0.16-8-macos-x64.url=https\://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.16%2B8/OpenJDK17U-jdk_x64_mac_hotspot_17.0.16_8.tar.gz
entry.temurin-17.0.16-8-macos-x64.sha256=ca5700c5d13124467ae52e1609881d7ce45d974870b18c3382ea8b7ae69d0f00
entry.temurin-17.0.16-8-macos-x64.javaHomeRelativePath=jdk-17.0.16+8/Contents/Home

entry.temurin-17.0.16-8-linux-x64.vendor=EclipseAdoptium
entry.temurin-17.0.16-8-linux-x64.javaMajor=17
entry.temurin-17.0.16-8-linux-x64.version=17.0.16
entry.temurin-17.0.16-8-linux-x64.build=8
entry.temurin-17.0.16-8-linux-x64.operatingSystem=Linux
entry.temurin-17.0.16-8-linux-x64.architecture=amd64
entry.temurin-17.0.16-8-linux-x64.archiveType=tar.gz
entry.temurin-17.0.16-8-linux-x64.url=https\://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.16%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.16_8.tar.gz
entry.temurin-17.0.16-8-linux-x64.sha256=166774efcf0f722f2ee18eba0039de2d685b350ee14d7b69e6f83437dafd2af1
entry.temurin-17.0.16-8-linux-x64.javaHomeRelativePath=jdk-17.0.16+8

entry.temurin-17.0.16-8-windows-x64.vendor=EclipseAdoptium
entry.temurin-17.0.16-8-windows-x64.javaMajor=17
entry.temurin-17.0.16-8-windows-x64.version=17.0.16
entry.temurin-17.0.16-8-windows-x64.build=8
entry.temurin-17.0.16-8-windows-x64.operatingSystem=Windows 11
entry.temurin-17.0.16-8-windows-x64.architecture=amd64
entry.temurin-17.0.16-8-windows-x64.archiveType=zip
entry.temurin-17.0.16-8-windows-x64.url=https\://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.16%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.16_8.zip
entry.temurin-17.0.16-8-windows-x64.sha256=8c7cfff78a55c56ebaf470ed6a89c6466b47d8274bdabdda997d7507c20325c5
entry.temurin-17.0.16-8-windows-x64.javaHomeRelativePath=jdk-17.0.16+8
